AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CodeChallengeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: challenge_tester/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          APP_TOKEN: CHANGETHIS
      Events:
        CodeChallenge:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /code
            Method: post
        MemoryCompare:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /memory
            Method: post
        Test:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /test
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CodeChallengeApi:
    Description: "API Gateway endpoint URL for Prod stage for Code Challenge function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/code/"
  CodeChallengeFunction:
    Description: "Code Challenge Lambda Function ARN"
    Value: !GetAtt CodeChallengeFunction.Arn
  CodeChallengeFunctionIamRole:
    Description: "Implicit IAM Role created for Code Challenge function"
    Value: !GetAtt CodeChallengeFunction.Arn
