# Generated by Django 3.0.3 on 2020-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='exercicios',
            field=models.ManyToManyField(to='core.Exercicio'),
        ),
    ]
