# Generated by Django 3.0.2 on 2020-01-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200130_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewDeExercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=1024, unique=True)),
                ('view', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
