# Generated by Django 3.1.3 on 2021-02-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210209_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengerepo',
            name='remote',
            field=models.CharField(max_length=1024),
        ),
    ]
