# Generated by Django 3.0.3 on 2020-03-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200317_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaexprogramacao',
            name='stdouts',
            field=models.TextField(blank=True),
        ),
    ]
