# Generated by Django 3.0.3 on 2020-05-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_respostaexprogramacao_stdouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='password',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
