# Generated by Django 3.1.3 on 2021-02-09 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_challenge', '0003_auto_20210105_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('question_type', models.CharField(choices=[('AL', 'all'), ('RD', 'random')], default='AL', max_length=2)),
                ('slug', models.SlugField(default=quiz.models.create_slug)),
                ('duration', models.PositiveIntegerField()),
                ('deadline', models.DateTimeField()),
                ('challenges', models.ManyToManyField(to='code_challenge.CodeChallenge')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
