# Generated by Django 3.1.3 on 2021-02-09 21:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveQuiz',
            new_name='UserQuiz',
        ),
    ]
