# Generated by Django 3.1.3 on 2021-02-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210209_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
