# Generated by Django 3.1.3 on 2021-02-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userquiz_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
