# Generated by Django 3.1.3 on 2021-02-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_challenge', '0003_auto_20210105_1906'),
        ('quiz', '0004_userquiz_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='challenges',
            field=models.ManyToManyField(to='code_challenge.CodeChallenge'),
        ),
    ]
