# Generated by Django 3.1.3 on 2021-02-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_userquiz_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='has_manual_assessment',
            field=models.BooleanField(default=False),
        ),
    ]
