# Generated by Django 3.1.3 on 2021-03-09 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_challenge', '0003_auto_20210105_1906'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0006_quiz_has_manual_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizChallengeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_grade', models.FloatField(default=0)),
                ('manual_grade', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_challenge.codechallenge')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('submissions', models.ManyToManyField(to='code_challenge.CodeChallengeSubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
