# Generated by Django 3.1.3 on 2021-03-13 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_challenge', '0003_auto_20210105_1906'),
        ('quiz', '0007_quizchallengefeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizchallengefeedback',
            name='submissions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='grading_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizchallengefeedback',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='code_challenge.codechallengesubmission'),
        ),
        migrations.AlterField(
            model_name='quizchallengefeedback',
            name='manual_grade',
            field=models.FloatField(null=True),
        ),
    ]
