# Generated by Django 3.1.3 on 2021-04-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_semester'),
        ('code_challenge', '0005_auto_20210409_2231'),
        ('quiz', '0008_auto_20210312_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExerciseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_grade_weight', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('available', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_weight', models.IntegerField(default=1)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
        ),
        migrations.CreateModel(
            name='SubChallengeGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_challenge.codechallenge')),
                ('code_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.codeexercisegrade')),
            ],
        ),
        migrations.CreateModel(
            name='QuizGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('available', models.BooleanField(default=False)),
                ('course_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.coursegrade')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='ExamGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('available', models.BooleanField(default=False)),
                ('course_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.coursegrade')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='codeexercisegrade',
            name='course_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.coursegrade'),
        ),
    ]
