# Generated by Django 3.1.3 on 2021-04-19 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeexercisegrade',
            name='course_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_exercises', to='grade.coursegrade'),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='course_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='grade.coursegrade'),
        ),
        migrations.AlterField(
            model_name='quizgrade',
            name='course_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='grade.coursegrade'),
        ),
        migrations.AlterField(
            model_name='subchallengegrade',
            name='code_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subchallenges', to='grade.codeexercisegrade'),
        ),
    ]
