# Generated by Django 3.1.3 on 2021-05-04 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_challenge', '0005_auto_20210409_2231'),
        ('grade', '0002_auto_20210419_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexercisegrade',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='codeexercisegrade',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubChallengeAutoFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.subchallengegrade')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_challenge.codechallengesubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
