# Generated by Django 3.1.3 on 2021-05-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0004_auto_20210505_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeexercisefeedback',
            name='manual_grade',
            field=models.FloatField(null=True),
        ),
    ]
