# Generated by Django 2.1.7 on 2019-02-28 21:45

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('report', '0002_evolutionreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialsReport',
            fields=[
            ],
            options={
                'verbose_name': 'Tutorials Report',
                'verbose_name_plural': 'Tutorials Reports',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
