# Generated by Django 2.1.7 on 2019-04-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_tutorialsreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvolutionReport',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='TutorialsReport',
        ),
    ]
