# Generated by Django 3.1.3 on 2020-12-18 22:01

import coding_challenge.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote', models.URLField()),
                ('slug', models.SlugField()),
                ('last_commit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodingChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('slug', models.SlugField()),
                ('question', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('show_stdout', models.BooleanField(default=True)),
                ('function_name', models.CharField(blank=True, max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.concept')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding_challenge.challengerepo')),
            ],
        ),
        migrations.CreateModel(
            name='UserChallengeInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('successful_attempts', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding_challenge.codingchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodingChallengeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('code', models.FileField(upload_to=coding_challenge.models.user_challenge_path)),
                ('success', models.BooleanField(default=False)),
                ('failures', models.JSONField(default=coding_challenge.models.empty_list)),
                ('stack_traces', models.JSONField(default=coding_challenge.models.empty_list)),
                ('stdouts', models.JSONField(default=coding_challenge.models.empty_list)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding_challenge.codingchallenge')),
            ],
        ),
    ]
