# Generated by Django 3.1.3 on 2020-12-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote', models.URLField()),
                ('slug', models.SlugField()),
                ('last_commit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('order', models.IntegerField(default=99)),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='CodingChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('slug', models.SlugField()),
                ('question', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('show_stdout', models.BooleanField(default=True)),
                ('function_name', models.CharField(blank=True, max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding_challenge.challengerepo')),
                ('tags', models.ManyToManyField(to='coding_challenge.Tag')),
            ],
        ),
    ]
