# Generated by Django 3.1.3 on 2020-12-19 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('slug', models.SlugField()),
                ('published', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.concept')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.challengerepo')),
            ],
        ),
    ]
