# Generated by Django 2.1.4 on 2019-01-30 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.DateTimeField(auto_now=True, verbose_name='date released')),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('description', models.TextField()),
                ('replit_url', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_access', models.DateTimeField(auto_now=True, verbose_name='first accessed')),
                ('access_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
