# Generated by Django 2.1.4 on 2019-01-21 17:48

import challenges.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.DateTimeField(auto_now=True, verbose_name='date released')),
                ('expire', models.DateTimeField(blank=True, null=True, verbose_name='date expired')),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('problem', models.TextField()),
                ('test_file', models.FileField(upload_to='challenge_tests/')),
                ('function_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('feedback', models.TextField(blank=True)),
                ('code', models.FileField(upload_to=challenges.models.user_directory_path)),
                ('result', models.CharField(blank=True, choices=[(challenges.models.Result('Erro'), 'Erro'), (challenges.models.Result('OK'), 'OK')], max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
            ],
        ),
    ]
