# Generated by Django 2.1.4 on 2019-02-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, upload_to='challenge/'),
        ),
    ]
