# Generated by Django 2.1.7 on 2019-04-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20190225_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='errors',
            field=models.TextField(blank=True),
        ),
    ]
