# Generated by Django 2.1.7 on 2019-08-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_challengesubmission_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
