# Generated by Django 2.1.7 on 2019-08-19 21:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challengesubmission_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='challengesubmission',
            managers=[
                ('objects_with_deleted', django.db.models.manager.Manager()),
            ],
        ),
    ]
