# Generated by Django 2.1.7 on 2019-09-27 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190718_1729'),
        ('challenges', '0008_auto_20190819_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='data inicial')),
                ('fim', models.DateTimeField(verbose_name='data final')),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('descricao', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('exercicios', models.ManyToManyField(to='challenges.Challenge')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Class')),
            ],
        ),
    ]
