# Generated by Django 2.1.7 on 2019-09-19 12:19

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20190819_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='test_file',
            field=models.FileField(blank=True, default=challenges.models.create_default_test_file, upload_to='challenge_tests/'),
        ),
    ]
