# Generated by Django 2.1.7 on 2019-09-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_auto_20190919_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='test_file',
            field=models.FileField(default='default_test_file', upload_to='challenge_tests/'),
        ),
    ]
