# Generated by Django 2.1.7 on 2019-10-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_auto_20190926_2321'),
        ('challenges', '0014_auto_20190919_0935'),
    ]

    operations = [
    ]
