# Generated by Django 2.1.7 on 2020-01-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0015_merge_20191001_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteDeMesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=1024)),
                ('descricao', models.TextField()),
                ('codigo', models.TextField()),
                ('gabarito', models.TextField()),
            ],
        ),
    ]
