# Generated by Django 2.1.7 on 2020-01-15 21:08

import challenges.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0016_testedemesa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testedemesa',
            options={'verbose_name_plural': 'testes de mesa'},
        ),
        migrations.AlterField(
            model_name='testedemesa',
            name='gabarito',
            field=models.TextField(validators=[challenges.validators.json_validator]),
        ),
    ]
