# Generated by Django 2.1.7 on 2020-01-20 21:37

import challenges.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0017_auto_20200115_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testedemesa',
            name='codigo',
            field=challenges.models.NonStrippingTextField(),
        ),
    ]
