# Generated by Django 2.1.7 on 2020-01-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_auto_20200120_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testedemesa',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
