# Generated by Django 3.1.3 on 2020-12-18 23:38

import code_challenge.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('slug', models.SlugField()),
                ('question', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('show_stdout', models.BooleanField(default=True)),
                ('function_name', models.CharField(blank=True, max_length=50)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CodeChallengeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('code', models.FileField(upload_to=code_challenge.models.user_challenge_path)),
                ('success', models.BooleanField(default=False)),
                ('failures', models.JSONField(default=code_challenge.models.empty_list)),
                ('stack_traces', models.JSONField(default=code_challenge.models.empty_list)),
                ('stdouts', models.JSONField(default=code_challenge.models.empty_list)),
            ],
        ),
        migrations.CreateModel(
            name='UserChallengeInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('successful_attempts', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_challenge.codechallenge')),
            ],
        ),
    ]
