# Generated by Django 3.1.3 on 2020-12-18 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallengeinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codechallengesubmission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codechallengesubmission',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_challenge.codechallenge'),
        ),
        migrations.AddField(
            model_name='codechallenge',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.concept'),
        ),
        migrations.AddField(
            model_name='codechallenge',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.challengerepo'),
        ),
    ]
