# Generated by Django 3.1.3 on 2021-01-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_challenge', '0002_auto_20201218_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechallenge',
            name='function_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
