# Generated by Django 3.1.3 on 2021-03-31 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_challenge', '0003_auto_20210105_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallengeinteraction',
            name='latest_submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='code_challenge.codechallengesubmission'),
        ),
    ]
